---
  version: '3.7'
  
  x-config:
    &secrets-config
    secrets:
      - source: tomcat_ssl_crt
        target: /home/spring/wildcard.crt
      - source: tomcat_ssl_key
        target: /home/spring/wildcard.key
        
  secrets:
    tomcat_ssl_crt:
      file: ./docker/certificates/wildcard.crt
    tomcat_ssl_key:
      file: ./docker/certificates/wildcard.key

  services:
    mlr-legacy:
      build: .
      image: mlr-legacy
      ports:
        - "6010:6010"
      << : *secrets-config
      volumes: 
      - ./docker/certificates/import_certs:/certificates:ro
      env_file:
        - ./docker/config.env
        - ./docker/secrets.env
      
    mlr-legacy-local-dev:
      build: .
      image: mlr-legacy
      network_mode: "host"
      ports:
        - "6010:6010"
      << : *secrets-config
      volumes: 
        - ./docker/certificates/import_certs:/certificates:ro
      env_file:
        - ./docker/config.env
        - ./docker/secrets.env

    mlr-legacy-debug:
      build: .
      image: mlr-legacy
      network_mode: "host"
      ports:
        - "6010:6010"
        - "8000:8000"
      << : *secrets-config
      volumes: 
        - ./docker/certificates/import_certs:/certificates:ro
      environment:
        - JAVA_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n"
      env_file:
        - ./docker/config.env
        - ./docker/secrets.env
