server:
  port: ${serverPort:8443}
  ssl:
    key-store: ${keystoreLocation}
    key-store-password: ${keystorePassword}
    key-password: ${keystorePassword}
    key-alias: ${keystoreSSLKey:tomcat}
    enabled-protocols: TLSv1.2

spring:
  datasource:
    url: "jdbc:postgresql://${mlrLegacyDbHost}:${mlrLegacyDbPort}/mlr_legacy"
    username: ${mlrLegacyDataUsername}
    password: ${mlrLegacyDataPassword}
    driver-class-name: org.postgresql.Driver
  profiles:
    active: default, swagger
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauthResourceJwkSetUri:}

mybatis:
  type-aliases-package: gov.usgs.wma.mlrlegacy
  type-handlers-package: gov.usgs.wma.mlrlegacy
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
  mapper-locations: "classpath:monitoringLocation.xml"

security:
  require-ssl: true
  basic:
    enabled: false

logging:
  level:
    root: ${rootLogLevel:info}
    org:
      springframework: ${springFrameworkLogLevel:info}

maintenanceRoles: ${maintenanceRoles}

springdoc:
  swagger-ui:
    path: /swagger-ui/api-docs.html