server:
  port: ${serverPort:8443}
  ssl:
    key-store: ${keystoreLocation}
    key-store-password: ${keystorePassword}
    key-password: ${keystorePassword}
    key-alias: ${keystoreSSLKey:tomcat}
    enabled-protocols: TLSv1.2

spring:
  datasource:
    url: "jdbc:postgresql://${mlrLegacyDbHost}:${mlrLegacyDbPort}/mlr_legacy"
    username: ${mlrLegacyDataUsername}
    password: ${mlrLegacyDataPassword}
    driver-class-name: org.postgresql.Driver
  profiles:
    active: default, swagger

mybatis:
  type-aliases-package: gov.usgs.wma.mlrlegacy
  type-handlers-package: gov.usgs.wma.mlrlegacy
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
  mapper-locations: "classpath:monitoringLocation.xml"

security:
  require-ssl: true
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ${oauthClientId}
      clientSecret: ${oauthClientSecret}
      accessTokenUri: ${oauthClientAccessTokenUri}
      userAuthorizationUri: ${oauthClientAuthorizationUri}
    resource:
      id: ${oauthResourceId}
      jwt:
        keyUri: ${oauthResourceTokenKeyUri}
  maintenanceRoles: ${maintenanceRoles:}

logging:
  level:
    root: ${rootLogLevel:info}
    org:
      springframework: ${springFrameworkLogLevel:info}
      
springdoc:
  swagger-ui:
    path: /swagger-ui/api-docs.html